version: "3.3"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
